### ISSUE TITLE
无法启动server

### ISSUE THREAD

**Issue by ice-leng** [FLemon/pin-sensation#1]
lengbindeMacBook-Pro:pin-sensation lengbin$ bundle exec puma -C config/puma.rb
Puma starting in single mode...
* Version 3.6.2 (ruby 2.3.3-p222), codename: Sleepy Sunday Serenity
* Min threads: 5, max threads: 5
* Environment: development
! Unable to load application: NoMethodError: undefined method `split' for nil:NilClass
bundler: failed to load command: puma (/usr/local/bin/puma)
NoMethodError: undefined method `split' for nil:NilClass
  /Users/lengbin/Documents/ruby/pin-sensation/config/initializers/devise.rb:253:in `block in <top (required)>'
  /usr/local/lib/ruby/gems/2.3.0/gems/devise-4.2.0/lib/devise.rb:292:in `setup'
  /Users/lengbin/Documents/ruby/pin-sensation/config/initializers/devise.rb:3:in `<top (required)>'
  /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
  /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `block in load'
  /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
  /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
  /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:648:in `block in load_config_initializer'
  /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/notifications.rb:166:in `instrument'
  /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:647:in `load_config_initializer'
  /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
  /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:611:in `each'
  /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:611:in `block in <class:Engine>'
  /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in `instance_exec'
  /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:55:in `block in run_initializers'
  /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
  /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
  /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
  /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:44:in `each'
  /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:44:in `tsort_each_child'
  /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/tsort.rb:415:in `call'
  /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
  /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `each'
  /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `call'
  /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
  /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
  /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
  /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:54:in `run_initializers'
  /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/application.rb:352:in `initialize!'
  /Users/lengbin/Documents/ruby/pin-sensation/config/environment.rb:5:in `<top (required)>'
  config.ru:3:in `require_relative'
  config.ru:3:in `block in <main>'
  /usr/local/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:55:in `instance_eval'
  /usr/local/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:55:in `initialize'
  config.ru:in `new'
  config.ru:in `<main>'
  /usr/local/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:49:in `eval'
  /usr/local/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:49:in `new_from_string'
  /usr/local/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:40:in `parse_file'
  /usr/local/lib/ruby/gems/2.3.0/gems/puma-3.6.2/lib/puma/configuration.rb:315:in `load_rackup'
  /usr/local/lib/ruby/gems/2.3.0/gems/puma-3.6.2/lib/puma/configuration.rb:243:in `app'
  /usr/local/lib/ruby/gems/2.3.0/gems/puma-3.6.2/lib/puma/runner.rb:127:in `load_and_bind'
  /usr/local/lib/ruby/gems/2.3.0/gems/puma-3.6.2/lib/puma/single.rb:85:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/puma-3.6.2/lib/puma/launcher.rb:172:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/puma-3.6.2/lib/puma/cli.rb:74:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/puma-3.6.2/bin/puma:10:in `<top (required)>'
  /usr/local/bin/puma:22:in `load'
  /usr/local/bin/puma:22:in `<top (required)>'
lengbindeMacBook-Pro:pin-sensation lengbin$

**Comment by FLemon** [comment]
你好 @ice-leng 
这个pin-sensation是个人项目，运行需要设置环境变量，例如谷歌登录的ID和Secret。你这个错误是因为有要一个domain需要设置(https://github.com/FLemon/pin-sensation/blob/master/config/initializers/devise.rb#L251)

初学不建议启动这个项目，我给这个项目做例子只是想让你看看capybara是怎么集成的。
